version: '3'

services:
  _build_image:
    image: main_image
    build: .
  nginx:
    build: ./nginx/nginx
    volumes:
      - static_volume:/usr/src/app/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    image: main_image
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - _build_image
  cron:
    image: main_image
    restart: always
    command: bash -c "service cron start && python manage.py crontab add && tail -f /dev/null"
    env_file:
      - ./.env
    depends_on:
      - web
volumes:
  static_volume:
