version: '3'

services:
  nginx:
    build: ./nginx/nginx_local
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
volumes:
  static_volume:
